steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:latest', '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']

images: ['gcr.io/$PROJECT_ID/$REPO_NAME']
