---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tht-api
  namespace: pangea
spec:
  replicas: 3
  selector:
    matchLabels:
      service: tht-api
      name: tht-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: tht-api
        name: tht-api
    spec:
      containers:
        - name: tht-api
          image: gcr.io/shining-fire-5514/github-pangeamart-api:v2.0.1-8
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 4000
              name: http
            - containerPort: 4466
              name: http
      volumes:
        - name: rethinkdb
          secret:
            secretName: rethink-rethinkdb
---
apiVersion: v1
kind: Service
metadata:
  name: tht-api
  namespace: tht
  labels:
    name: tht-api
    service: tht-api
    env: production
    role: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      name: http
      targetPort: 4000
      protocol: TCP
    - port: 4466
      name: http
      targetPort: 4466
      protocol: TCP
  selector:
    name: tht-api
