---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tht-api
  namespace: tht
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tht-api
      name: tht-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: tht-api
        name: tht-api
    spec:
      containers:
        - name: tht-api
          image: gcr.io/trans-helping-trans/github_jbowden1982_trans-helping-trans-api:latest
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 4000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: tht-api
  namespace: tht
  labels:
    name: tht-api
    service: tht-api
    env: production
    role: loadbalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: api.transhelpingtrans.xyz.
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      name: http2
      targetPort: 4000
      protocol: TCP
    - port: 80
      name: http
      targetPort: 4000
      protocol: TCP
    - port: 443
      name: https
      targetPort: 4000
      protocol: TCP
  selector:
    name: tht-api
