apiVersion: v1
kind: Service
metadata:
  name: tht-api
  namespace: tht
  annotations:
    external-dns.alpha.kubernetes.io/hostname: socket.pangeamart.com.
  labels:
    name: tht-api
    service: tht-api
    env: production
    role: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 4000
      name: http
      targetPort: 4000
      protocol: TCP
    - port: 4466
      name: http
      targetPort: 4466
      protocol: TCP
  selector:
    name: tht-api
